#!/bin/sh

run_hook() {
	local TOP=/mnt/btrfs-root

	mkdir -p "${TOP}" &&
		mount -o subvol=/ -L ROOT "${TOP}" || return 1

	if [ -d "${TOP}/root.bak" ]; then
		rec-sub-del.sh root.bak "${TOP}" || return 1
	fi
	# This will, as always, not snapshot any subvolumes below root.next (but
	# there shouldn't be any)
	btrfs subvolume snapshot "${TOP}/root.next" "${TOP}/root.bak" || return 1

	umount "${TOP}" &&
		rmdir "${TOP}" || return 1
}
