---
- hosts: pclab
  tasks:
  - name: Install mariadb
    block:
    - name: Install mariadb package
      pacman:
        name: mariadb
        state: present
    - name: Initialize mariadb
      command: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
    - name: Start mariadb service
      service:
        name: mysqld
        state: started
    - name: Secure mariadb
      command: mysql_secure_installation
      args:
        stdin: "\nn\ny\ny\ny\ny\n"
    - name: Create labuser database and user
      command: mysql -u root
      args:
        stdin: |
          CREATE DATABASE labuserdb;
          CREATE USER labuser@localhost IDENTIFIED BY 'labuser';
          GRANT ALL PRIVILEGES ON labuserdb.* TO 'labuser'@'localhost';
          FLUSH PRIVILEGES;
    - name: Set mariadb to only listen on loopback
      lineinfile:
        path: /etc/my.cnf.d/server.cnf
        insertafter: '^\[mysqld\]'
        line: "bind-address=127.0.0.1"
        state: present
    - name: Disable mariadb service
      service:
        name: mysqld
        state: stopped
        enabled: no
    - name: Allow labuser to start mariadb service
      lineinfile:
        path: /etc/sudoers
        line: 'labuser ALL=(ALL) NOPASSWD: /usr/bin/systemctl start mysqld'
        state: present
    - name: Add script for labuser to start mariadb service
      copy:
        content: |
          #!/bin/sh
          sudo systemctl start mysqld
        dest: /home/labuser/opt/bin/start_mysql
        owner: labuser
        group: labuser
        mode: 0755
    tags:
    - mariadb
  
  - name: Install phpmyadmin
    block:
    - name: Install phpmyadmin package
      pacman:
        name: phpmyadmin
        state: present
    - name: Enable php extensions for mysql
      lineinfile:
        path: /etc/php/php.ini
        regexp: '^;extension={{ item }}'
        line: "extension={{ item }}"
      with_items:
      - pdo_mysql
      - mysqli
    - name: Add script for labuser to run phpmyadmin
      copy:
        content: |
          #!/bin/sh
          cd /usr/share/webapps/phpMyAdmin
          php -S localhost:8000
        dest: /home/labuser/opt/bin/start_phpmyadmin
        owner: labuser
        group: labuser
        mode: 0755
    tags:
    - phpmyadmin