---
- name: Upgrade system
  hosts: pclab
  tasks:
  - name: Upgrade system
    # NOTE: The upgrade is performed in parts, to avoid problems when upgrading
    # after a long time.
    block:
    - name: Upgrade archlinux-keyring
      community.general.pacman:
        name: archlinux-keyring
        state: latest
        update_cache: yes
    - name: Upgrade pacman
      community.general.pacman:
        name: pacman
        state: latest
        update_cache: yes
    - name: Upgrade everything
      community.general.pacman:
        update_cache: yes
        upgrade: yes
    # TODO OPT: Check for and report any .pacnew and .pacsave
    tags:
    - always
    - upgrade
  # TODO OPT: Perform the above upgrades via the roles too (using tags), to
  # include packages possibly added post initial installation.
  - name: Upgrade pip packages
    include_role:
      name: extra
    tags:
    - never
    - pip
  - name: Persist changes
    import_tasks: persist.yml
